"""Add personal_records table

Revision ID: 749d68860a29
Revises: d5f6a7b8c9d0
Create Date: 2026-03-26 07:14:45.937742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '749d68860a29'
down_revision: Union[str, Sequence[str], None] = 'd5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_record_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('estimated_1rm', sa.Float(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise_library.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_record_history_exercise_id'), 'personal_record_history', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_personal_record_history_user_id'), 'personal_record_history', ['user_id'], unique=False)
    op.create_table('personal_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('estimated_1rm', sa.Float(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('previous_1rm', sa.Float(), nullable=True),
    sa.Column('improvement_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise_library.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exercise_id', name='uq_pr_user_exercise')
    )
    op.create_index(op.f('ix_personal_records_exercise_id'), 'personal_records', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_personal_records_user_id'), 'personal_records', ['user_id'], unique=False)
    op.drop_index(op.f('ix_food_items_name'), table_name='food_items')
    op.create_unique_constraint(None, 'user_achievements', ['user_id', 'achievement_id'])
    op.alter_column('user_progress', 'total_workouts',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_progress', 'missions_completed_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_unique_constraint(None, 'user_skill_tree', ['user_id', 'node_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_skill_tree', type_='unique')
    op.alter_column('user_progress', 'missions_completed_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_progress', 'total_workouts',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'user_achievements', type_='unique')
    op.create_index(op.f('ix_food_items_name'), 'food_items', [sa.literal_column('lower(name::text)')], unique=False)
    op.drop_index(op.f('ix_personal_records_user_id'), table_name='personal_records')
    op.drop_index(op.f('ix_personal_records_exercise_id'), table_name='personal_records')
    op.drop_table('personal_records')
    op.drop_index(op.f('ix_personal_record_history_user_id'), table_name='personal_record_history')
    op.drop_index(op.f('ix_personal_record_history_exercise_id'), table_name='personal_record_history')
    op.drop_table('personal_record_history')
    # ### end Alembic commands ###
